#!/usr/bin/env python3
"""Vendor the parity corpus into the repo and emit its manifest.

Today the 882-ish-model parity result depends on a gitignored symlink tree
pointing at four *external* model repos (BNGL-Models, RuleHub, RuleMonkey,
BNGL_library), so nobody else can reproduce it. This script COPIES every
selected model into a tracked tree under ``tests/parity/models/`` and writes a
single ``tests/parity/manifest.json`` that is the reproducible source of truth
for the suite.

Model SELECTION + tiers come from the per-model keys of the canonical per-tier
parity reports (``--report tier=path`` pairs). Each model is resolved to its
real file (the reports reference symlinks), classified by source, and copied to

    tests/parity/models/<tier>/<source>/<relpath-under-source-root>/<model>.bngl

preserving basenames (the verdict registries + overrides are basename/stem
keyed). Non-.bngl companion files beside a selected model (includes, .net /
scan data) are copied alongside it so relative-path includes still resolve.

The manifest keys each record by its **vendored relpath** (collision-free —
12 basenames collide across sources), and carries: source, license,
upstream provenance (repo + commit SHA), tier, regime, the expected verdict
bucket (derived from the parity_diff registries), and any per-model overrides
(t_end cap, n_scan_pts, tol, action-inject, timeout) lifted
from parity_sweep. parity_sweep can then read overrides FROM the manifest by
relpath id, which removes the basename-collision ambiguity of its hardcoded
dicts. The verdict-reason registries stay in parity_diff.py.

A ``tests/parity/NOTICE`` is written with per-source attribution + SHAs + the
MIT license text for the MIT-licensed sources.
"""

import argparse
import importlib.util
import json
import shutil
import subprocess
from pathlib import Path

HOME = Path.home()

# Source roots: a resolved model path is made relative to its source root to
# form the vendored <source>/<rel> sub-path. Mirrors build_candidate_corpus.py.
SOURCE_ROOTS = {
    "bngl_models": HOME / "Code" / "BNGL-Models",
    "rulehub": HOME / "Code" / "RuleHub",
    "rulemonkey": HOME / "Code" / "RuleMonkey",
    "bngl_library": HOME / "Code" / "BNGL_library" / "bngl_models",
}

# Per-source license metadata for the manifest + NOTICE. SHAs are filled in at
# runtime from each repo's git HEAD.
SOURCE_META = {
    "bngl_models": {
        "repo": "github.com/wshlavacek/BNGL-Models",
        "license": "MIT",
        "note": "Bill Hlavacek; literature-derived BNGL models.",
    },
    "rulehub": {
        "repo": "github.com/RuleWorld/RuleHub",
        "license": "MIT",
        "note": "RuleWorld curated BNGL/BioNetGen content.",
    },
    "rulemonkey": {
        "repo": "github.com/richardposner/RuleMonkey",
        "license": "MIT",
        "note": "Richard Posner; RuleMonkey test models.",
    },
    "bngl_library": {
        "repo": "local (no public remote)",
        "license": "unspecified",
        "note": "Local BNGL library; redistributed by repo-owner consent.",
    },
    "curated": {
        "repo": "derived in-repo",
        "license": "MIT (derived from RuleHub)",
        "note": "Generated by scripts/curate_creamer.py from RuleHub Creamer2012.",
    },
}

# Tier order for resolving a model that appears in more than one tier report:
# the slower tier wins (its DIFF cost dominates how the suite must run it).
TIER_RANK = {"fast": 0, "slow": 1, "glacial": 2, "original": 1}

SCRIPTS = Path(__file__).resolve().parent
REPO = SCRIPTS.parent
CREAMER_FIXTURE = REPO / "tests" / "models" / "Creamer_2012.bngl"


def _load_module(name):
    spec = importlib.util.spec_from_file_location(name, SCRIPTS / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def load_registries():
    """Expected-bucket map (stem -> bucket) + override dicts, from the scripts."""
    pd = _load_module("parity_diff")
    ps = _load_module("parity_sweep")
    expected = {}
    for stem in (
        set(pd.SUBPROCESS_NF_UNRELIABLE)
        | set(pd.SUBPROCESS_NF_ANALYTIC)
        | set(pd.SUBPROCESS_NF_RULEMONKEY)
    ):
        expected[stem] = "PASS_REF_BUG"
    for stem in set(pd.KNOWN_DETERMINISTIC_ARTIFACTS) | set(pd.KNOWN_STOCHASTIC_ARTIFACTS):
        expected[stem] = "KNOWN_ARTIFACT"
    overrides = {
        "t_end": ps.TEND_OVERRIDES,
        "n_scan_pts": ps.NSCANPTS_OVERRIDES,
        "action_inject": ps.ACTION_INJECT,
        "tol": ps.TOL_OVERRIDES,
        "timeout": ps.TIMEOUT_OVERRIDES,
    }
    return expected, overrides


def classify(real: Path):
    """Return (source, rel_under_source) for a resolved model path."""
    s = str(real)
    if real == CREAMER_FIXTURE.resolve():
        return "curated", Path(real.name)
    for src, root in SOURCE_ROOTS.items():
        rr = str(root.resolve())
        if s.startswith(rr + "/"):
            return src, real.relative_to(root.resolve())
    # Fall back to a coarse marker so the run fails loudly rather than silently
    # mis-filing a model.
    raise ValueError(f"cannot classify source of {real}")


# Sibling files a BNGL model can actually load at runtime. Everything else
# beside a model (PyBNF .exp/.conf/.yaml, READMEs, figures, fit outputs, C++
# source) is fitter/doc noise we must NOT vendor.
RUNTIME_COMPANION_EXTS = {".net", ".species", ".tfun"}


def needed_companions(model_real: Path, model_text: str):
    """Sibling files this model needs: runtime-loadable ext OR named in text.

    A blanket copy of every sibling pulls in ~50MB of PyBNF/doc noise. BNG
    loads a sibling only if the model references it (readFile / table function /
    species file) or it is one of the few network/species/table-function
    formats. We copy a sibling iff its name appears verbatim in the model text
    OR its extension is runtime-loadable.
    """
    out = []
    parent = model_real.parent
    if not parent.is_dir():
        return out
    for sib in parent.iterdir():
        if not sib.is_file() or sib.suffix.lower() == ".bngl":
            continue
        if sib.name.startswith(".") or sib.name == ".DS_Store":
            continue
        if sib.suffix.lower() in RUNTIME_COMPANION_EXTS or sib.name in model_text:
            out.append(sib)
    return out


def overrides_for(basename, overrides):
    """Collect the per-model overrides (keyed by basename in parity_sweep)."""
    out = {}
    for key, table in overrides.items():
        if basename in table:
            out[key] = table[basename]
    return out


def git_sha(root: Path):
    try:
        return (
            subprocess.run(
                ["git", "-C", str(root), "rev-parse", "HEAD"], capture_output=True, text=True
            ).stdout.strip()
            or None
        )
    except Exception:
        return None


def collect(reports):
    """Build {real_path: record-stub} from the per-tier reports."""
    recs = {}
    for tier, rep in reports.items():
        d = json.loads(Path(rep).read_text())
        for k, info in d["per_model"].items():
            real = Path(k).resolve()
            if not real.exists():
                print(f"!! missing (skipped): {k}")
                continue
            cur = recs.get(real)
            if cur is None:
                recs[real] = {"real": real, "tier": tier, "regime": info.get("regime")}
            else:
                # Keep the slower tier; keep a regime if we didn't have one.
                if TIER_RANK.get(tier, 1) > TIER_RANK.get(cur["tier"], 1):
                    cur["tier"] = tier
                cur["regime"] = cur.get("regime") or info.get("regime")
    return recs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--report",
        action="append",
        required=True,
        metavar="TIER=PATH",
        help="canonical per-tier parity report (repeat). "
        "e.g. --report fast=dev/.../parity_report_FINAL.json",
    )
    ap.add_argument(
        "--dest", default=str(REPO / "tests" / "parity"), help="output dir (default tests/parity)"
    )
    ap.add_argument(
        "--dry-run", action="store_true", help="report what would be vendored; copy nothing"
    )
    args = ap.parse_args()

    reports = {}
    for spec in args.report:
        tier, _, path = spec.partition("=")
        if not path:
            ap.error(f"--report must be TIER=PATH, got {spec!r}")
        reports[tier] = path

    expected_map, overrides = load_registries()
    shas = {src: git_sha(root) for src, root in SOURCE_ROOTS.items()}

    recs = collect(reports)
    dest = Path(args.dest)
    models_root = dest / "models"

    manifest = []
    n_copy = n_companion = 0
    for real, stub in sorted(recs.items(), key=lambda kv: str(kv[0])):
        source, rel = classify(real)
        vrel = Path(stub["tier"]) / source / rel  # vendored relpath = id
        vpath = models_root / vrel
        ov = overrides_for(real.name, overrides)
        stem = real.stem
        record = {
            "id": vrel.as_posix(),
            "file": (Path("models") / vrel).as_posix(),
            "basename": real.name,
            "source": source,
            "license": SOURCE_META[source]["license"],
            "provenance": {
                "repo": SOURCE_META[source]["repo"],
                "commit": shas.get(source),
                "path": str(rel),
            },
            "tier": stub["tier"],
            "regime": stub.get("regime"),
            "expected": expected_map.get(stem, "PASS"),
        }
        if ov:
            record["overrides"] = ov
        manifest.append(record)

        if not args.dry_run:
            vpath.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(real, vpath)
            n_copy += 1
            # Copy only the siblings this model can actually load (runtime ext
            # or named in the model text), into the same vendored dir, so
            # relative includes / .net / table-function data resolve. Per-model
            # (not per-dir) so a source dir split across tiers is handled.
            for sib in needed_companions(real, vpath.read_text(errors="replace")):
                cdst = vpath.parent / sib.name
                if not cdst.exists():
                    shutil.copy2(sib, cdst)
                    n_companion += 1

    manifest.sort(key=lambda r: r["id"])
    by_tier = {}
    by_source = {}
    by_bucket = {}
    for r in manifest:
        by_tier[r["tier"]] = by_tier.get(r["tier"], 0) + 1
        by_source[r["source"]] = by_source.get(r["source"], 0) + 1
        by_bucket[r["expected"]] = by_bucket.get(r["expected"], 0) + 1

    if not args.dry_run:
        dest.mkdir(parents=True, exist_ok=True)
        (dest / "manifest.json").write_text(
            json.dumps(
                {
                    "schema": "parity-corpus/1",
                    "n_models": len(manifest),
                    "sources": {s: {**SOURCE_META[s], "commit": shas.get(s)} for s in by_source},
                    "models": manifest,
                },
                indent=2,
            )
            + "\n"
        )
        write_notice(dest, by_source, shas)

    print(f"models: {len(manifest)}")
    print(f"  by tier:   {by_tier}")
    print(f"  by source: {by_source}")
    print(f"  expected:  {by_bucket}")
    if args.dry_run:
        print("(dry-run: nothing copied)")
    else:
        print(f"copied {n_copy} models + {n_companion} companion files -> {models_root}")
        print(f"manifest: {dest / 'manifest.json'}")


MIT_TEXT = (
    "Permission is hereby granted, free of charge, to any person obtaining a "
    "copy\nof this software and associated documentation files ...\n"
    "(standard MIT terms; see each upstream repository for the full text).\n"
)


def write_notice(dest, by_source, shas):
    lines = [
        "Parity corpus — third-party model attribution",
        "=" * 46,
        "",
        "The BNGL models under tests/parity/models/ are vendored copies of models",
        "from the repositories below, included for simulator-parity testing. Each",
        "model's upstream source + commit is recorded in tests/parity/manifest.json",
        "(per-model `provenance`).",
        "",
    ]
    for src in sorted(by_source):
        m = SOURCE_META[src]
        lines += [
            f"[{src}]  ({by_source[src]} models)",
            f"  upstream: {m['repo']}",
            f"  commit:   {shas.get(src) or '(n/a)'}",
            f"  license:  {m['license']}",
            f"  note:     {m['note']}",
            "",
        ]
    lines += ["", "MIT License (RuleHub, RuleMonkey, BNGL-Models):", "", MIT_TEXT]
    (dest / "NOTICE").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
